### ISSUE TITLE
Allow using a pipe for RPC stderr

### ISSUE THREAD

**Issue by hifi** [deltachat/deltachat-rpc-client-go#1]
The initial interface to disable/forward stderr uses `*os.File` which is quite inflexible if you want to redirect or even reformat the log output. Would be handy to be able to use a pipe to process it manually.

Project itself looking good so far!

**Comment by adbenitez** [comment]
hi @hifi, thanks a lot for your feedback, I fixed it in e1dd210b6f521e3fe4762061fc38240796d67558 it is released in `v0.10.0` already

**Comment by adbenitez** [comment]
btw, if you are looking to create bots rather than Delta Chat clients, take a look at https://github.com/deltachat-bot/deltabot-cli-go it helps to minimize the repetitive boilerplate of bot CLI creation so you can focus on message/events processing

**Comment by hifi** [comment]
Thanks for getting that fixed so fast! 

I'm actually working on a Matrix bridge based on Mautrix (go) to Delta Chat and will release the WIP version soon on GH once I get it creating rooms for chats and passing messages both directions.

**Comment by adbenitez** [comment]
> I'm actually working on a Matrix bridge

super cool! :100: share the link here once it is published, I would also like to share it with friends

**Comment by adbenitez** [comment]
if you have questions about the API and the delta chat core, you can join the #Delta.Chat:matrix.org room or https://irc.masfloss.net/#deltachat
